import { open } from 'node:fs/promises';

// These envelopes are generated by Claude Code, not typed user turns. Match
// only known leading wrappers, so ordinary prose, XML and pasted code survive.
export function isUserPrompt(text: string): boolean {
  const prompt = text.trimStart();
  return Boolean(prompt.trim()) && !prompt.startsWith('/')
    && !/^<(?:task-notification|teammate-message|local-command-(?:stdout|stderr|caveat)|command-name|command-message)(?:\s|>)/.test(prompt);
}

export function userPromptPreview(text: string): string {
  return text.replace(/<\/?pasted_content(?:\s+id=(?:"[^"]*"|'[^']*'))?\s*>/g, '')
    .trim().slice(0, 200).replace(/[\n\t\r]/g, ' ');
}

export function userTextFromRecord(record: unknown): string | undefined {
  if (!record || typeof record !== 'object') return undefined;
  const r = record as Record<string, unknown>;
  if (r['type'] !== 'user' || r['isMeta'] === true || r['isCompactSummary'] === true) return undefined;
  const message = r['message'];
  if (!message || typeof message !== 'object') return undefined;
  const content = (message as Record<string, unknown>)['content'];
  const text = typeof content === 'string' ? content : Array.isArray(content)
    ? content.filter((part) => part?.type === 'text' && typeof part.text === 'string').map((part) => part.text).join('\n') : '';
  return isUserPrompt(text) ? text : undefined;
}

export async function readTranscriptRegion(path: string): Promise<string> {
  const fd = await open(path, 'r');
  try {
    const { size } = await fd.stat();
    const start = Math.max(0, size - 1_048_576);
    const buf = Buffer.alloc(size - start);
    const { bytesRead } = await fd.read(buf, 0, buf.length, start);
    const text = buf.subarray(0, bytesRead).toString('utf8');
    const newline = text.indexOf('\n');
    return start > 0 ? (newline >= 0 ? text.slice(newline + 1) : '') : text;
  } finally { await fd.close(); }
}

// Repair the displayed prompt from older state without guessing historical
// turn counts or loading an unbounded transcript on every statusline render.
export async function readLatestUserPrompt(path: string | undefined): Promise<string> {
  if (!path) return '';
  try {
    const lines = (await readTranscriptRegion(path)).split('\n');
    for (let i = lines.length - 1; i >= 0; i--) {
      try {
        const text = userTextFromRecord(JSON.parse(lines[i]!));
        if (text !== undefined) return userPromptPreview(text);
      } catch { /* incomplete trailing or malformed record */ }
    }
  } catch { /* missing transcript: show the normal placeholder */ }
  return '';
}
